package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Drifter</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--leather:#8b5e3c;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif;min-height:100vh}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:1100px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase;letter-spacing:0.05em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;align-items:flex-start}select,input,textarea{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem}.form-row select,.form-row input{flex:1}textarea{width:100%;min-height:80px;resize:vertical}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.full{grid-column:1/-1}.badge-g{background:#1a3a1a;color:#5cb85c;border:1px solid #2d5a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-r{background:#3a1a1a;color:#d9534f;border:1px solid #5a2d2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-y{background:#3a2f1a;color:#f0ad4e;border:1px solid #5a4a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}</style></head>
<body><header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Drifter</span><span class="badge">Feature Flags</span></header>
<main><div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Flags</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Evaluations</div></div><div class="stat"><div class="stat-value" id="s3">FREE</div><div class="stat-label">Tier</div></div></div><div class="grid">
<div class="card"><h2>New Flag</h2>
<div class="form-row"><input id="f-key" placeholder="new-checkout-flow"></div>
<div class="form-row"><input id="f-desc" placeholder="Description"></div>
<div class="form-row"><input id="f-rollout" type="number" value="100" placeholder="Rollout %"><label style="color:var(--muted);font-size:0.82rem;padding:0.5rem">% rollout</label></div>
<button class="btn" onclick="createFlag()">Create Flag</button></div>
<div class="card"><h2>Test Evaluation</h2>
<div class="form-row"><input id="t-key" placeholder="flag-key"></div>
<div class="form-row"><input id="t-user" placeholder="user-id (for rollout)"></div>
<button class="btn" onclick="testFlag()">Evaluate</button>
<div id="t-result" style="margin-top:0.75rem;font-size:0.9rem"></div>
<div style="margin-top:1rem;padding-top:1rem;border-top:1px solid var(--border)">
<h2>Eval All</h2>
<div class="form-row"><input id="all-user" placeholder="user-id"></div>
<button class="btn btn-sm" onclick="evalAll()">Get All Flags</button>
<div id="all-result" style="margin-top:0.5rem;font-size:0.8rem;color:var(--leather);font-family:monospace;white-space:pre-wrap"></div></div></div>
<div class="card full"><h2>Flags</h2>
<table><thead><tr><th>Key</th><th>Status</th><th>Rollout</th><th>Description</th><th></th></tr></thead>
<tbody id="flags-body"><tr><td colspan="5" class="empty">No flags</td></tr></tbody></table></div>
</div></main>
<script>
async function api(m,p,bd){var o={method:m,headers:{"Content-Type":"application/json"}};if(bd)o.body=JSON.stringify(bd);var r=await fetch(p,o);try{return await r.json();}catch(e){return {};}}  
async function load(){var s=await api("GET","/api/stats");var l=await api("GET","/api/limits");document.getElementById("s1").textContent=s.flags||0;document.getElementById("s2").textContent=s.evals||0;document.getElementById("s3").textContent=(l.tier||"free").toUpperCase();loadFlags();}
async function loadFlags(){var data=await api("GET","/api/flags");var tbody=document.getElementById("flags-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='5' class='empty'>No flags</td></tr>";return;}tbody.innerHTML=data.map(function(f){return "<tr><td style='color:var(--cream);font-family:monospace'>"+f.key+"</td><td><span class='badge-"+(f.enabled?"g":"r")+"'>"+( f.enabled?"on":"off")+"</span></td><td>"+f.rollout_percent+"%</td><td style='color:var(--muted);font-size:0.82rem'>"+f.description+"</td><td style='display:flex;gap:0.25rem'><button class='btn btn-sm' onclick='toggleFlag(\""+f.key+"\")'>Toggle</button><button class='btn btn-sm btn-danger' onclick='deleteFlag(\""+f.key+"\")'>Del</button></td></tr>";}).join("");}
async function createFlag(){var f={key:document.getElementById("f-key").value.trim(),description:document.getElementById("f-desc").value.trim(),rollout_percent:parseInt(document.getElementById("f-rollout").value)||100,enabled:false};if(!f.key){alert("Key required");return;}var res=await api("POST","/api/flags",f);if(res.error){alert(res.error);return;}document.getElementById("f-key").value="";load();}
async function toggleFlag(key){await api("POST","/api/flags/"+key+"/toggle");load();}
async function deleteFlag(key){if(!confirm("Delete flag?"))return;await api("DELETE","/api/flags/"+key);load();}
async function testFlag(){var key=document.getElementById("t-key").value.trim();var user=document.getElementById("t-user").value.trim();if(!key){alert("Key required");return;}var res=await api("GET","/api/eval?key="+encodeURIComponent(key)+"&user_id="+encodeURIComponent(user));document.getElementById("t-result").innerHTML="<span class='badge-"+(res.enabled?"g":"r")+"'>"+(res.enabled?"ENABLED":"DISABLED")+"</span> (rollout: "+(res.rollout||0)+"%)";load();}
async function evalAll(){var user=document.getElementById("all-user").value.trim();var res=await api("GET","/api/eval/all?user_id="+encodeURIComponent(user));document.getElementById("all-result").textContent=JSON.stringify(res,null,2);}
load();
</script></body></html>`)
